config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'
  get 'signin', to: redirect('/auth/google_oauth2'), as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  resources :sessions, only: [:create, :destroy]

  root to: "pets#index"

  resources :pets

  
  resources :pets, except: [:show] do
    post "/like", to: "pets#like_toggle"
    post "/report", to: "pets#report_toggle"
 end

end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :pet
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :likes
  has_many :reports
end

app/models/report.rb
class Report < ActiveRecord::Base
    belongs_to :user
    belongs_to :pet
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :likes
    has_many :reports
    has_many :pets
  
    def is_Like?(pet)
       Like.find_by(user_id: self.id, pet_id: pet.id).present?
    end
   
    def is_Report?(pet)
    Report.find_by(user_id: self.id, pet_id: pet.id).present?
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def authenticate
    redirect_to :signin unless user_signed_in?
  end

  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  #   rescue ActiveRecord::RecordNotFound
  # end
 def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
    def user_signed_in?
    # converts current_user to a boolean by negating the negation
    !!current_user
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
    def mypet
        @pets = Pet.where("user_id = ?", current_user.id)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
    #@pets = Pet.order("created_at DESC").page(params[:page]).per(10)
    @pet = Pet.new
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to "/pets"
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    @pet.update(pet_params)
    redirect_to "/pets/#{pet_id}"
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    redirect_to "/pets"
  end

  def like
    @likes = Like.where("user_id = ?", current_user.id)
  end

  def like_toggle
    bookmark = Like.find_by(user_id: current_user.id, pet_id: params[:pet_id])
     if bookmark.nil?
        Like.create(user_id: current_user.id, pet_id: params[:pet_id])
       else
        bookmark.destroy
       end
       redirect_to :back
    end
    
  def report
    @reports = Report.where("user_id = ?", current_user.id)
  end

  def report_toggle
    flag = Report.find_by(user_id: current_user.id, pet_id: params[:pet_id])
     if flag.nil?
        Report.create(user_id: current_user.id, pet_id: params[:pet_id])
       else
        flag.destroy
       end
       redirect_to :back
    end
    
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:user_id, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to :pets
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
  def from_omniauth(auth)
    user = User.where(provider: auth.provider, uid: auth.uid).first_or_initialize
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save
    return user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CYU</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
<div class="field">
<%= f.label :image %><br>
<%= f.file :image %>
</div>
<div class="actions">
<%= f.submit %>
</div>
<% end %>

app/views/pets/index.html.erb
<html>
<!--
//기능: 날짜, 좋아요, 삭제(신고)
//필요 페이지: 메인페이지, 사진보여주는페이지, 글작성페이지, 로그인페이지 (4)
-->
<head>
  <meta charset="UTF-8" />
  <link href="https://fonts.googleapis.com/css?family=Happy+Monkey|Major+Mono+Display" rel="stylesheet">
  <link rel="stylesheet" href="style.css" />
  <link rel="stylesheet" href="/assets/upload.css" />
  <script src="http://code.jquery.com/jquery-latest.js"></script>
  <script type="text/javascript" src="/assets/script.js"></script>
</head>
  <body id="body">
    <div class="container" id="container">



<!-- HEADING -->
      <div class="heading">
        <%= image_tag ("logo.png"), id: "logo" %>
        <hr />
        <ul class="flex-container">
          <li class="flex-item">
            <a href="/" class="selected">home</a>
          </li>
          <li class="flex-item">
            <a href="#" class="btn_toggle"> upload </a>
          </li>
          <li class="flex-item">
            <% if current_user %>
              <a href="/signout" >logout</a>
            <% else %>
              <a href="/signin" id="login">login</a>
            <% end %>
          </li>
             <% if current_user %>
          <li class="flex-item">
          <%=current_user.name =%>님 안녕하세요 ! 
          </li>
            <% end %>

        </ul>
        <hr />
      </div>


    <%= form_for(@pet) do |f| %>
            <div class="upload">
            <% if current_user %>
              <%= f.file_field :image, :class => "image" %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <input type="submit" name="submit" class="submitFile" value="UPLOAD IMAGE">
            <% else %>
            you should login first
            <% end %>
            </div>
    <% end %>

<!-- IMAGE MANSONRY -->
      <div class="masonry">
        <% @pets.each do |pet| %>
        <div class="item1">
            <%= image_tag (pet.image) %>
          <div class="img-caption1 bottom-top1">
            <br>
            <% if current_user %>
              <% if current_user.is_Like?(pet) %>
                <%= link_to t(:heart_html), pet_like_path(pet), method: "post", class: "symbol-size" %>
              <% else %>
                <%= link_to t(:heartempty_html), pet_like_path(pet), method: "post", class: "symbol-size" %>
              <% end %>
              <% if current_user.is_Report?(pet) %>
                <%= link_to t(:flag_html), pet_report_path(pet), method: "post", class: "symbol-size" %>
                <% else %>
                <%= link_to t(:flagempty_html), pet_report_path(pet), method: "post", class: "symbol-size" %>
              <% end %>
              <% if current_user.id == pet.user_id %>
                <%= link_to t(:destroy_html), pet, method: :delete, data: {confirms: 'Are you sure?'}, class: "symbol-size3" %>
              <% end %>
            <% end %>
          <br>
            <%= pet.likes.count %>명이 좋아합니다.
          <br>
          </div>
        </div>
      <% end %>
      </div>


    </div>
  </body>
</html>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pet.description %>
</p>

<p>
  <strong>Image:</strong>
<%= image_tag @pet.image.thumb.url %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %>
<%= link_to 'Back', pets_path %>

<% if current_user.is_Like?(@pet) %>
<%= link_to 'Like_yes', pet_like_path(@pet), method: "post" %>
<% else %>
<%= link_to 'Like_no', pet_like_path(@pet), method: "post" %>
<% end %>

<% if current_user.is_Report?(@pet) %>
<%= link_to 'Report_yes', pet_report_path(@pet), method: "post" %>
<% else %>
<%= link_to 'Report_no', pet_report_path(@pet), method: "post" %>
<% end %>